apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sandbox-k8s-jobs
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: myjob
              image: 'gcr.io/app-name/image:tag'
              # TODO: Attempt to use dynamic value for argument.
              # See: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments
              args:
                - /bin/bash
                - ./run.sh
          restartPolicy: Never
